# Generated by Django 6.0.4 on 2026-04-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
