# Generated by Django 6.0.4 on 2026-05-09 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pharmacy_inventory_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription_review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_status',
            field=models.CharField(choices=[('not_required', 'Nao exige receita'), ('pending', 'Aguardando analise'), ('approved', 'Receita aprovada'), ('rejected', 'Receita recusada')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacyinventory',
            name='promotion_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacyinventory',
            name='promotion_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pharmacyinventory',
            name='promotion_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pharmacyinventory',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
