# Generated by Django 6.0.4 on 2026-05-10 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_prescription_review_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Principal', max_length=60)),
                ('recipient_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=150, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
                'ordering': ('-is_default', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.order')),
            ],
            options={
                'verbose_name': 'Historico de status',
                'verbose_name_plural': 'Historicos de status',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('manual', 'Manual')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('manual', 'Manual'), ('gateway_not_configured', 'Gateway nao configurado'), ('error', 'Erro')], default='pending', max_length=30)),
                ('payment_method', models.CharField(choices=[('pix', 'Pix'), ('credit_card', 'Cartao de credito'), ('debit_card', 'Cartao de debito'), ('cash', 'Dinheiro na entrega')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('qr_code', models.TextField(blank=True, default='')),
                ('qr_code_base64', models.TextField(blank=True, default='')),
                ('payment_url', models.URLField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='core.order')),
            ],
            options={
                'verbose_name': 'Transacao de pagamento',
                'verbose_name_plural': 'Transacoes de pagamento',
                'ordering': ('-created_at',),
            },
        ),
    ]
