# Generated by Django 6.0.4 on 2026-05-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_address_orderstatushistory_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='cep',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
