# Generated by Django 6.0.4 on 2026-05-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pharmacy_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_process', 'Em processamento'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('manual', 'Manual'), ('gateway_not_configured', 'Gateway nao configurado'), ('error', 'Erro')], default='pending', max_length=30),
        ),
    ]
