# Generated by Django 6.0.4 on 2026-05-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_deactivate_legacy_default_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_card_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit', 'Cartão de crédito'), ('debit', 'Cartão de débito')], max_length=10, null=True),
        ),
    ]
