from django.urls import path
from .views import (
    dashboard_view,
    home,
    login_view,
    logout_view,
    register_view,
    password_recovery_view,
    profile_view,
    payment_view,
    prescription_upload_view,
    orders_view,
    pharmacy_dashboard_view,
    pharmacy_register_view,
    pharmacy_inventory_view,
    pharmacy_inventory_update,
    pharmacy_orders_view,
    pharmacy_prescriptions_view,
    help_view,
    prescription_document_view,
    add_to_cart,
    add_inventory_to_cart,
    cart_view,
    checkout_view,
    clear_cart,
    decrease_cart_item,
    remove_cart_item,
)
from .api_views import (
    api_address,
    api_addresses,
    api_cart,
    api_cart_add,
    api_cart_item,
    api_catalog,
    api_checkout,
    api_health,
    api_login,
    api_logout,
    api_me,
    api_orders,
    api_register,
)

urlpatterns = [
    path('api/health/', api_health, name='api_health'),
    path('api/auth/register/', api_register, name='api_register'),
    path('api/auth/login/', api_login, name='api_login'),
    path('api/auth/logout/', api_logout, name='api_logout'),
    path('api/me/', api_me, name='api_me'),
    path('api/catalog/', api_catalog, name='api_catalog'),
    path('api/cart/', api_cart, name='api_cart'),
    path('api/cart/items/', api_cart_add, name='api_cart_add'),
    path('api/cart/items/<int:item_id>/', api_cart_item, name='api_cart_item'),
    path('api/addresses/', api_addresses, name='api_addresses'),
    path('api/addresses/<int:address_id>/', api_address, name='api_address'),
    path('api/checkout/', api_checkout, name='api_checkout'),
    path('api/orders/', api_orders, name='api_orders'),
    path('', home, name='home'),
    path('login/', login_view, name='login'),
    path('registro/', register_view, name='registro'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('recuperar-senha/', password_recovery_view, name='recuperar_senha'),
    path('logout/', logout_view, name='logout'),
    path('perfil/', profile_view, name='perfil'), 
    path('pagamento/', payment_view, name='pagamento'),     
    path('ajuda/', help_view, name='ajuda'),     
    path('pedidos/', orders_view, name='orders'),
    path('carrinho/', cart_view, name='cart'),
    path('concluir-pedido/', checkout_view, name='checkout'),
    path('receita-digital/', prescription_upload_view, name='prescription_upload'),
    path('receitas/<int:order_id>/arquivo/', prescription_document_view, name='prescription_document'),
    path('farmacia/', pharmacy_dashboard_view, name='pharmacy_dashboard'),
    path('farmacia/cadastro/', pharmacy_register_view, name='pharmacy_register'),
    path('farmacia/<int:pharmacy_id>/estoque/', pharmacy_inventory_view, name='pharmacy_inventory'),
    path('farmacia/estoque/<int:inventory_id>/editar/', pharmacy_inventory_update, name='pharmacy_inventory_update'),
    path('farmacia/<int:pharmacy_id>/pedidos/', pharmacy_orders_view, name='pharmacy_orders'),
    path('farmacia/<int:pharmacy_id>/receitas/', pharmacy_prescriptions_view, name='pharmacy_prescriptions'),
    path('carrinho/adicionar/<int:medicine_id>/', add_to_cart, name='add_to_cart'),
    path('carrinho/adicionar-estoque/<int:inventory_id>/', add_inventory_to_cart, name='add_inventory_to_cart'),
    path('carrinho/diminuir/<int:item_id>/', decrease_cart_item, name='decrease_cart_item'),
    path('carrinho/remover/<int:item_id>/', remove_cart_item, name='remove_cart_item'),
    path('carrinho/limpar/', clear_cart, name='clear_cart'),
]
