from django.urls import path
from .views import (
    about,
    contact,
    dashboard_view,
    home,
    login_view,
    logout_view,
    register_view,
    password_recovery_view,
    profile_view,
    payment_view,
    prescription_upload_view,
    orders_view,
    pharmacy_auth_view,
    pharmacy_dashboard_view,
    pharmacy_register_view,
    pharmacy_inventory_view,
    pharmacy_inventory_update,
    pharmacy_inventory_delete,
    pharmacy_orders_view,
    pharmacy_prescriptions_view,
    help_view,
    prescription_document_view,
    add_to_cart,
    add_inventory_to_cart,
    cart_view,
    checkout_view,
    clear_cart,
    decrease_cart_item,
    remove_cart_item,
)

urlpatterns = [
    path('', home, name='home'),
    path('quem-somos/', about, name='about'),
    path('contato/', contact, name='contact'),
    path('login/', login_view, name='login'),
    path('registro/', register_view, name='registro'),
    path('farmacia/auth/', pharmacy_auth_view, name='pharmacy_auth'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('recuperar-senha/', password_recovery_view, name='recuperar_senha'),
    path('logout/', logout_view, name='logout'),
    path('perfil/', profile_view, name='perfil'), 
    path('pagamento/', payment_view, name='pagamento'),     
    path('ajuda/', help_view, name='ajuda'),     
    path('pedidos/', orders_view, name='orders'),
    path('carrinho/', cart_view, name='cart'),
    path('concluir-pedido/', checkout_view, name='checkout'),
    path('receita-digital/', prescription_upload_view, name='prescription_upload'),
    path('receitas/<int:order_id>/arquivo/', prescription_document_view, name='prescription_document'),
    path('farmacia/', pharmacy_dashboard_view, name='pharmacy_dashboard'),
    path('farmacia/cadastro/', pharmacy_register_view, name='pharmacy_register'),
    path('farmacia/<int:pharmacy_id>/estoque/', pharmacy_inventory_view, name='pharmacy_inventory'),
    path('farmacia/estoque/<int:inventory_id>/editar/', pharmacy_inventory_update, name='pharmacy_inventory_update'),
    path('farmacia/estoque/<int:inventory_id>/excluir/', pharmacy_inventory_delete, name='pharmacy_inventory_delete'),
    path('farmacia/<int:pharmacy_id>/pedidos/', pharmacy_orders_view, name='pharmacy_orders'),
    path('farmacia/<int:pharmacy_id>/receitas/', pharmacy_prescriptions_view, name='pharmacy_prescriptions'),
    path('carrinho/adicionar/<int:medicine_id>/', add_to_cart, name='add_to_cart'),
    path('carrinho/adicionar-estoque/<int:inventory_id>/', add_inventory_to_cart, name='add_inventory_to_cart'),
    path('carrinho/diminuir/<int:item_id>/', decrease_cart_item, name='decrease_cart_item'),
    path('carrinho/remover/<int:item_id>/', remove_cart_item, name='remove_cart_item'),
    path('carrinho/limpar/', clear_cart, name='clear_cart'),
]
